### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by PackmanDude** [PackmanDude/balancity-gnu-linux-fix#1]
```
chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:30043
function c(a){throw a;}var d=void 0,aa=!0,ba=null,ca=!1,e;e||(e=eval("(function() { try { return Module || {} } catch(e) { return {} } })()"));var da={},ea;for(ea in e)e.hasOwnProperty(ea)&&(da[ea]=e[ea]);var fa="object"===typeof process&&"function"===typeof require,ga="object"===typeof window,ia="function"===typeof importScripts,ja=!ga&&!fa&&!ia;
              ^

RangeError: Maximum call stack size exceeded
    at Object.cr.appendArray (chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:536:10)
    at GridCell_.dump (chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:1450:6)
    at SparseGrid_.queryRange (chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:1285:10)
    at Runtime.getCollisionCandidates (chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:5887:23)
    at Runtime.getTypesCollisionCandidates (chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:5909:9)
    at Runtime.getJumpthruCollisionCandidates (chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:5924:8)
    at Runtime.testOverlapJumpThru (chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:6343:8)
    at behinstProto.onCreate (chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:32404:39)
    at Runtime.createInstanceFromInit (chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:5726:11)
    at Runtime.createInstance (chrome-extension://kbppgaebokfahefoblahomldnmmiabgb/c2runtime.js:5544:15)
```

**Comment by PackmanDude** [comment]
Seems to be a performance issue, not a bug.
